import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="min-h-screen flex flex-col">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col flex-grow`}>
        <header className='flex shadow-md py-4 px-4 sm:px-10 bg-white font-[sans-serif] min-h-[70px] tracking-wide relative z-50'>
          <div className='flex flex-wrap items-center justify-between gap-5 w-full'>
            <a href="#"><img src="https://readymadeui.com/readymadeui.svg" alt="logo" className='w-36' />
            </a>

            <div id="collapseMenu"
              className='max-lg:hidden lg:!block max-lg:before:fixed max-lg:before:bg-black max-lg:before:opacity-50 max-lg:before:inset-0 max-lg:before:z-50'>
              <button id="toggleClose" className='lg:hidden fixed top-2 right-4 z-[100] rounded-full bg-white p-3'>
                <svg xmlns="http://www.w3.org/2000/svg" className="w-4 fill-black" viewBox="0 0 320.591 320.591">
                  <path
                    d="M30.391 318.583a30.37 30.37 0 0 1-21.56-7.288c-11.774-11.844-11.774-30.973 0-42.817L266.643 10.665c12.246-11.459 31.462-10.822 42.921 1.424 10.362 11.074 10.966 28.095 1.414 39.875L51.647 311.295a30.366 30.366 0 0 1-21.256 7.288z"
                    data-original="#000000"></path>
                  <path
                    d="M287.9 318.583a30.37 30.37 0 0 1-21.257-8.806L8.83 51.963C-2.078 39.225-.595 20.055 12.143 9.146c11.369-9.736 28.136-9.736 39.504 0l259.331 257.813c12.243 11.462 12.876 30.679 1.414 42.922-.456.487-.927.958-1.414 1.414a30.368 30.368 0 0 1-23.078 7.288z"
                    data-original="#000000"></path>
                </svg>
              </button>

              <ul
                className='lg:flex gap-x-5 max-lg:space-y-3 max-lg:fixed max-lg:bg-white max-lg:w-1/2 max-lg:min-w-[300px] max-lg:top-0 max-lg:left-0 max-lg:p-6 max-lg:h-full max-lg:shadow-md max-lg:overflow-auto z-50'>
                <li className='mb-6 hidden max-lg:block'>
                  <a href="#"><img src="https://readymadeui.com/readymadeui.svg" alt="logo" className='w-36' />
                  </a>
                </li>
                <li className='max-lg:border-b border-gray-300 max-lg:py-3 px-3'>
                  <a href='#'
                    className='hover:text-[#007bff] text-[#007bff] block font-semibold text-[15px]'>Home</a>
                </li>
                <li className='max-lg:border-b border-gray-300 max-lg:py-3 px-3'><a href='#'
                    className='hover:text-[#007bff] text-gray-500 block font-semibold text-[15px]'>Team</a>
                </li>
                <li className='max-lg:border-b border-gray-300 max-lg:py-3 px-3'><a href='#'
                    className='hover:text-[#007bff] text-gray-500 block font-semibold text-[15px]'>Feature</a>
                </li>
                <li className='max-lg:border-b border-gray-300 max-lg:py-3 px-3'><a href='#'
                    className='hover:text-[#007bff] text-gray-500 block font-semibold text-[15px]'>Blog</a>
                </li>
                <li className='max-lg:border-b border-gray-300 max-lg:py-3 px-3'><a href='#'
                    className='hover:text-[#007bff] text-gray-500 block font-semibold text-[15px]'>About</a>
                </li>
                <li className='max-lg:border-b border-gray-300 max-lg:py-3 px-3'><a href='#'
                    className='hover:text-[#007bff] text-gray-500 block font-semibold text-[15px]'>Contact</a>
                </li>
              </ul>
            </div>

            <div className='flex max-lg:ml-auto space-x-3'>
              <button
                className='px-4 py-2 text-sm rounded-full font-bold text-white border-2 border-[#007bff] bg-[#007bff] transition-all ease-in-out duration-300 hover:bg-transparent hover:text-[#007bff]'>Login</button>
              <button
                className='px-4 py-2 text-sm rounded-full font-bold text-white border-2 border-[#007bff] bg-[#007bff] transition-all ease-in-out duration-300 hover:bg-transparent hover:text-[#007bff]'>Sign
                up</button>

              <button id="toggleOpen" className='lg:hidden'>
                <svg className="w-7 h-7" fill="#000" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                  <path fillRule="evenodd"
                    d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
                    clipRule="evenodd"></path>
                </svg>
              </button>
            </div>
          </div>
        </header>
        <main className="flex-grow">
          {children}
        </main>
        <footer className="font-sans tracking-wide bg-[#213343] py-10 px-10">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
            <div>
              <h4 className="text-[#FFA726] font-semibold text-lg mb-6">Quick Links</h4>
              <ul className="space-y-5">
                <li>
                  <a href="#" className="hover:text-[#FFA726] text-gray-300 text-[15px] transition-all">Our Story</a>
                </li>
                <li>
                  <a href="#" className="hover:text-[#FFA726] text-gray-300 text-[15px] transition-all">Newsroom</a>
                </li>
                <li>
                  <a href="#" className="hover:text-[#FFA726] text-gray-300 text-[15px] transition-all">Careers</a>
                </li>
                <li>
                  <a href="#" className="hover:text-[#FFA726] text-gray-300 text-[15px] transition-all">Blog</a>
                </li>
              </ul>
            </div>

        <div>
          <h4 className="text-[#FFA726] font-semibold text-lg mb-6">Services</h4>
          <ul className="space-y-5">
            <li>
              <a href="#" className="hover:text-[#FFA726] text-gray-300 text-[15px] transition-all">Web Development</a>
            </li>
            <li>
              <a href="#" className="hover:text-[#FFA726] text-gray-300 text-[15px] transition-all">Testing Automation</a>
            </li>
            <li>
              <a href="#" className="hover:text-[#FFA726] text-gray-300 text-[15px] transition-all">AWS Development Services</a>
            </li>
            <li>
              <a href="#" className="hover:text-[#FFA726] text-gray-300 text-[15px] transition-all">Mobile App Development</a>
            </li>
          </ul>
        </div>

        <div>
          <h4 className="text-[#FFA726] font-semibold text-lg mb-6">Platforms</h4>
          <ul className="space-y-5">
            <li>
              <a href="#" className="hover:text-[#FFA726] text-gray-300 text-[15px] transition-all">Hubspot</a>
            </li>
            <li>
              <a href="#" className="hover:text-[#FFA726] text-gray-300 text-[15px] transition-all">Marketo Integration Services</a>
            </li>
            <li>
              <a href="#" className="hover:text-[#FFA726] text-gray-300 text-[15px] transition-all">Marketing Glossary</a>
            </li>
            <li>
              <a href="#" className="hover:text-[#FFA726] text-gray-300 text-[15px] transition-all">UIPath</a>
            </li>
          </ul>
        </div>

        <div>
          <h4 className="text-[#FFA726] font-semibold text-lg mb-6">Company</h4>
          <ul className="space-y-5">
            <li>
              <a href="#" className="hover:text-[#FFA726] text-gray-300 text-[15px] transition-all">Accessibility</a>
            </li>
            <li>
              <a href="#" className="hover:text-[#FFA726] text-gray-300 text-[15px] transition-all">About</a>
            </li>
            <li>
              <a href="#" className="hover:text-[#FFA726] text-gray-300 text-[15px] transition-all">Contact</a>
            </li>
            <li>
              <a href="#" className="hover:text-[#FFA726] text-gray-300 text-[15px] transition-all">Learn more</a>
            </li>
          </ul>
        </div>
      </div>

      <div className="border-t text-center border-[#6b5f5f] pt-8 mt-8">
        <p className="text-gray-300 text-[15px]">© ReadymadeUI. All rights reserved.</p>
      </div>
    </footer>
      </body>
    </html>
  )
}
