const express = require('express')
const app = express()
const dbConnect = require('./config/db/dbConnect')
const route = require('./routes/route')
const cookies = require('cookie-parser')
require('dotenv').config()
app.use(cookies())  
app.use(express.json())
app.use(express.urlencoded({ extended: true }))
dbConnect.connect()
route(app)
app.listen(process.env.POST, ()=> {
    console.log('Server is running on port 3004')
})